sonar.projectKey=baby-growth-chart
sonar.projectName=baby-growth-chart
sonar.host.url=http://192.168.1.137:9000
sonar.token=sqp_f5c194aa160bd350537014cff0896f639249eab1

# Fuentes
sonar.sources=.
# Exclusiones típicas
sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**,**/__pycache__/**

# Si es Python
sonar.python.version=3.11

# Si es un proyecto con tests y quieres coverage
# sonar.python.coverage.reportPaths=coverage.xml